### ISSUE TITLE
An interesting paper

### ISSUE THREAD

**Issue by dabrahams** [jeffreykegler/personal#13]
Sorry if this isn't the best way to reach you; I've forgotten how we were in touch before.  I just thought you might be interested in this paper: https://arxiv.org/pdf/1902.06591

**Comment by v-jkegler** [comment]
For stuff of this nature, it's actually not a bad way to reach me.  And it's an interesting looking paper, though at first glance not an easy one.  I've downloaded it.

**Comment by jeffreykegler** [comment]
For stuff of this nature, it's actually not a bad way to reach me. And it's an interesting looking paper, though at first glance not an easy one. I've downloaded it.
