### ISSUE TITLE
Parsing with derivatives

### ISSUE THREAD

**Issue by jtolds** [jeffreykegler/personal#2]
Your timeline is amazing.

I'm so sorry for opening a Github issue on your personal page but I can't help myself - I feel like a parsing timeline is incomplete without at least a brief mention of the [2010 Yacc is Dead](https://arxiv.org/abs/1010.5023) paper and [follow-on discussion](http://matt.might.net/articles/parsing-with-derivatives/). It's a seemingly novel proposal on parsing using derivatives of grammars. Something you had seen before?

**Comment by jeffreykegler** [comment]
Could I ask you to re-ask the question on either the Marpa IRC channel or
our Google group (whichever you prefer).  That way our discussion is more
conveniently accessible to the Marpa community.  Thanks!

**Comment by jeffreykegler** [comment]
But, yes, I had seen the Might/Darais algorithm, and I blogged about it:
http://jeffreykegler.github.io/Ocean-of-Awareness-blog/individual/2010/12/killing-yacc-1-2-3.html
