### ISSUE TITLE
Missing explicit mention of operator-precedence grammars

### ISSUE THREAD

**Issue by mapio** [jeffreykegler/personal#4]
Dear Jeffrey, I'm reading your parsing timeline with great interest. It's a treasure trove of references and a very interesting read. I've just one question: I'm not an expert in parsing history, but I see you mention operator precedence a lot, but it seems that you never explicitly cite "Syntactic Analysis and Operator Precedence" by Floyd, R. W.  (appeared on Journal of the ACM, 1963).

Is there a specific reason for this?

**Comment by jeffreykegler** [comment]
Thanks for your interest and the kind words.

I used a narrative approach and avoided topics which didn't contribute to
my narrative, either by being part of the motivation (negative or positive)
for Marpa, or by being important for the mainstream practice of parsing.
As a result, I didn't deal with bounded-context parsing at all.

**Comment by mapio** [comment]
I see, it makes perfect sense.
