### ISSUE TITLE
Samuelson -> Samelson

### ISSUE THREAD

**Issue by kschmid** [jeffreykegler/personal#7]
Throughout the parsing time line Samelson is referenced as Samuelson. This is also the case for some literature references, though they are sometimes mixed (Key as Samuelson and author Samelson). 

(Thanks a lot for writing this! I greatly enjoyed reading it!)

**Comment by jeffreykegler** [comment]
Thanks for the kind words, and for the fix.

Fixed in the commits just mentioned, and pushed.
